version: "2.2"

networks:
  bridge-dev:
    driver: bridge

services:
  config-service:
    build: ./api-config-service
    container_name: config-service
    environment:
      - CONFIG_GIT_URL='https://github.com/wiliantv/Microservicos-API-config-repo.git'
    networks:
      - bridge-dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-service:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 60
  discovery-service:
    build: ./api-discovery-service
    depends_on:
      configservice:
        condition: service_healthy
    ports:
      - 8071:8071
    container_name: discovery-service
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
    networks:
      - bridge-dev
  apigateway:
    build: ./apigateway
    depends_on:
      configservice:
        condition: service_healthy
    ports:
      - 8080:8080
    container_name: apigateway
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
    networks:
      - bridge-dev