spring:
  application:
    name: admin-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}




logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
